version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: css-loader
    versions:
    - 5.2.0
    - 5.2.1
